package blog.pojo.po.view;

import java.util.Date;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table v_message_answer
 */
public class MessageAnswerView {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.user_avatar
     *
     * @mbg.generated
     */
    private String userAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.message_id
     *
     * @mbg.generated
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.send_user_id
     *
     * @mbg.generated
     */
    private Integer sendUserId;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.send_user_name
     *
     * @mbg.generated
     */
    private String sendUserName;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.send_user_avatar
     *
     * @mbg.generated
     */
    private String sendUserAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_message_answer.message_type
     *
     * @mbg.generated
     */
    private Boolean messageType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.id
     *
     * @return the value of v_message_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.id
     *
     * @param id the value for v_message_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.content
     *
     * @return the value of v_message_answer.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.content
     *
     * @param content the value for v_message_answer.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.user_id
     *
     * @return the value of v_message_answer.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.user_id
     *
     * @param userId the value for v_message_answer.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.nick_name
     *
     * @return the value of v_message_answer.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.nick_name
     *
     * @param nickName the value for v_message_answer.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.user_avatar
     *
     * @return the value of v_message_answer.user_avatar
     *
     * @mbg.generated
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.user_avatar
     *
     * @param userAvatar the value for v_message_answer.user_avatar
     *
     * @mbg.generated
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.message_id
     *
     * @return the value of v_message_answer.message_id
     *
     * @mbg.generated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.message_id
     *
     * @param messageId the value for v_message_answer.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.create_time
     *
     * @return the value of v_message_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.create_time
     *
     * @param createTime the value for v_message_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.update_time
     *
     * @return the value of v_message_answer.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.update_time
     *
     * @param updateTime the value for v_message_answer.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.status
     *
     * @return the value of v_message_answer.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.status
     *
     * @param status the value for v_message_answer.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.article_id
     *
     * @return the value of v_message_answer.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.article_id
     *
     * @param articleId the value for v_message_answer.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.send_user_id
     *
     * @return the value of v_message_answer.send_user_id
     *
     * @mbg.generated
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.send_user_id
     *
     * @param sendUserId the value for v_message_answer.send_user_id
     *
     * @mbg.generated
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.send_user_name
     *
     * @return the value of v_message_answer.send_user_name
     *
     * @mbg.generated
     */
    public String getSendUserName() {
        return sendUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.send_user_name
     *
     * @param sendUserName the value for v_message_answer.send_user_name
     *
     * @mbg.generated
     */
    public void setSendUserName(String sendUserName) {
        this.sendUserName = sendUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.send_user_avatar
     *
     * @return the value of v_message_answer.send_user_avatar
     *
     * @mbg.generated
     */
    public String getSendUserAvatar() {
        return sendUserAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.send_user_avatar
     *
     * @param sendUserAvatar the value for v_message_answer.send_user_avatar
     *
     * @mbg.generated
     */
    public void setSendUserAvatar(String sendUserAvatar) {
        this.sendUserAvatar = sendUserAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_message_answer.message_type
     *
     * @return the value of v_message_answer.message_type
     *
     * @mbg.generated
     */
    public Boolean getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_message_answer.message_type
     *
     * @param messageType the value for v_message_answer.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(Boolean messageType) {
        this.messageType = messageType;
    }
}