server:
  port: 8888 #内置tomcat端口
  tomcat:
    uri-encoding: UTF-8 #URL字符编码
  servlet:
    session:
      timeout: 30m #session生命周期

spring:
  datasource:
    username: rootall
    password: 123456
    url: jdbc:mysql://47.107.165.217:3306/sunly_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapping/*.xml,classpath:/mapping/custom/*.xml
  type-aliases-package: blog.pojo.mapper
  configuration:
    #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    cache-enabled: true
    aggressiveLazyLoading: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false # pageSize=0
