package blog.pojo.po;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_article_category
 */
public class ArticleCategory {
    /**
     * Database Column Remarks:
     *   博客类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   状态：启用/停用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_category.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_category.id
     *
     * @return the value of t_article_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_category.id
     *
     * @param id the value for t_article_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_category.name
     *
     * @return the value of t_article_category.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_category.name
     *
     * @param name the value for t_article_category.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_category.status
     *
     * @return the value of t_article_category.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_category.status
     *
     * @param status the value for t_article_category.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}