package blog.pojo.po;

import java.util.Date;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table v_article_message
 */
public class ArticleMessageView {
    /**
     * Database Column Remarks:
     *   留言id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   父留言id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   文章id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     * Database Column Remarks:
     *   状态：显示/隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   文章标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     * Database Column Remarks:
     *   留言内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_article_message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.id
     *
     * @return the value of v_article_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.id
     *
     * @param id the value for v_article_message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.create_time
     *
     * @return the value of v_article_message.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.create_time
     *
     * @param createTime the value for v_article_message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.update_time
     *
     * @return the value of v_article_message.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.update_time
     *
     * @param updateTime the value for v_article_message.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.user_id
     *
     * @return the value of v_article_message.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.user_id
     *
     * @param userId the value for v_article_message.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.parent_id
     *
     * @return the value of v_article_message.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.parent_id
     *
     * @param parentId the value for v_article_message.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.article_id
     *
     * @return the value of v_article_message.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.article_id
     *
     * @param articleId the value for v_article_message.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.status
     *
     * @return the value of v_article_message.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.status
     *
     * @param status the value for v_article_message.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.nick_name
     *
     * @return the value of v_article_message.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.nick_name
     *
     * @param nickName the value for v_article_message.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.article_title
     *
     * @return the value of v_article_message.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.article_title
     *
     * @param articleTitle the value for v_article_message.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_article_message.content
     *
     * @return the value of v_article_message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_article_message.content
     *
     * @param content the value for v_article_message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}