package blog.pojo.po;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_link
 */
public class Link {
    /**
     * Database Column Remarks:
     *   友链id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   友链名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   友链地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   友链介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.about
     *
     * @mbg.generated
     */
    private String about;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态：显示/隐藏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_link.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.id
     *
     * @return the value of t_link.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.id
     *
     * @param id the value for t_link.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.name
     *
     * @return the value of t_link.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.name
     *
     * @param name the value for t_link.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.address
     *
     * @return the value of t_link.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.address
     *
     * @param address the value for t_link.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.about
     *
     * @return the value of t_link.about
     *
     * @mbg.generated
     */
    public String getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.about
     *
     * @param about the value for t_link.about
     *
     * @mbg.generated
     */
    public void setAbout(String about) {
        this.about = about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.create_time
     *
     * @return the value of t_link.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.create_time
     *
     * @param createTime the value for t_link.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.update_time
     *
     * @return the value of t_link.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.update_time
     *
     * @param updateTime the value for t_link.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.status
     *
     * @return the value of t_link.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.status
     *
     * @param status the value for t_link.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}