package blog.pojo.po;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_setting
 */
public class Setting {
    /**
     * Database Column Remarks:
     *   设置id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   网站名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   网站LOGO
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * Database Column Remarks:
     *   网站版权
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.copyright
     *
     * @mbg.generated
     */
    private String copyright;

    /**
     * Database Column Remarks:
     *   修改日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   网站状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   网站备案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.icp
     *
     * @mbg.generated
     */
    private String icp;

    /**
     * Database Column Remarks:
     *   网站标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     * Database Column Remarks:
     *   网站介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_setting.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.id
     *
     * @return the value of t_setting.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.id
     *
     * @param id the value for t_setting.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.name
     *
     * @return the value of t_setting.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.name
     *
     * @param name the value for t_setting.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.icon
     *
     * @return the value of t_setting.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.icon
     *
     * @param icon the value for t_setting.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.copyright
     *
     * @return the value of t_setting.copyright
     *
     * @mbg.generated
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.copyright
     *
     * @param copyright the value for t_setting.copyright
     *
     * @mbg.generated
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.update_time
     *
     * @return the value of t_setting.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.update_time
     *
     * @param updateTime the value for t_setting.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.status
     *
     * @return the value of t_setting.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.status
     *
     * @param status the value for t_setting.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.icp
     *
     * @return the value of t_setting.icp
     *
     * @mbg.generated
     */
    public String getIcp() {
        return icp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.icp
     *
     * @param icp the value for t_setting.icp
     *
     * @mbg.generated
     */
    public void setIcp(String icp) {
        this.icp = icp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.tag
     *
     * @return the value of t_setting.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.tag
     *
     * @param tag the value for t_setting.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_setting.summary
     *
     * @return the value of t_setting.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_setting.summary
     *
     * @param summary the value for t_setting.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }
}