package blog.pojo.mapper;

import blog.pojo.po.ArticleCategory;
import blog.pojo.po.Example.ArticleCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    long countByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int insert(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int insertSelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    List<ArticleCategory> selectByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    ArticleCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleCategory record, @Param("example") ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleCategory record, @Param("example") ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleCategory record);
}