package blog.pojo.mapper;

import blog.pojo.po.ArticleMessage;
import blog.pojo.po.Example.ArticleMessageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ArticleMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    long countByExample(ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int insert(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int insertSelective(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    List<ArticleMessage> selectByExampleWithBLOBs(ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    List<ArticleMessage> selectByExample(ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    ArticleMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleMessage record, @Param("example") ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleMessage record, @Param("example") ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleMessage record, @Param("example") ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleMessage record);
}