package blog.pojo.mapper;

import blog.pojo.po.Diary;
import blog.pojo.po.Example.DiaryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    long countByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int deleteByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    List<Diary> selectByExampleWithBLOBs(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    List<Diary> selectByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    Diary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Diary record);
}