package blog.pojo.mapper;

import blog.pojo.po.Setting;
import blog.pojo.po.Example.SettingExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    long countByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int deleteByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int insertSelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    List<Setting> selectByExampleWithBLOBs(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    List<Setting> selectByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    Setting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Setting record);
}