package blog.pojo.mapper.view;

import blog.pojo.po.ArticleMainView;
import blog.pojo.po.Example.ArticleMainViewExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ArticleMainViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_article_main
     *
     * @mbg.generated
     */
    long countByExample(ArticleMainViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_article_main
     *
     * @mbg.generated
     */
    List<ArticleMainView> selectByExampleWithBLOBs(ArticleMainViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_article_main
     *
     * @mbg.generated
     */
    List<ArticleMainView> selectByExample(ArticleMainViewExample example);
}