package blog.pojo.mapper.view;

import blog.pojo.po.ArticleMessageView;
import blog.pojo.po.Example.ArticleMessageViewExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ArticleMessageViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_article_message
     *
     * @mbg.generated
     */
    long countByExample(ArticleMessageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_article_message
     *
     * @mbg.generated
     */
    List<ArticleMessageView> selectByExampleWithBLOBs(ArticleMessageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_article_message
     *
     * @mbg.generated
     */
    List<ArticleMessageView> selectByExample(ArticleMessageViewExample example);
}