package blog.pojo.mapper.view;

import blog.pojo.po.view.MessageAnswerView;
import blog.pojo.po.view.example.MessageAnswerViewExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MessageAnswerViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_message_answer
     *
     * @mbg.generated
     */
    long countByExample(MessageAnswerViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_message_answer
     *
     * @mbg.generated
     */
    List<MessageAnswerView> selectByExample(MessageAnswerViewExample example);
}