package blog.pojo.mapper.view;

import blog.pojo.po.view.MessageView;
import blog.pojo.po.view.example.MessageViewExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface MessageViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_message
     *
     * @mbg.generated
     */
    long countByExample(MessageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_message
     *
     * @mbg.generated
     */
    List<MessageView> selectByExample(MessageViewExample example);
}